require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

# We use `gems.rb` in this project
Bundler/GemFilename:
  EnforcedStyle: gems.rb
