language: ruby
services:
  - docker
rvm:
  - ruby-head
  - 2.7
  - 2.6
  - 2.5
  - 2.4
  - 2.3
matrix:
  allow_failures:
    - rvm: ruby-head
install:
  - docker build --tag verapdf-verifier .
  - docker run -d -p 80:80 --name verapdf-verifier verapdf-verifier
script:
  - docker exec -it verapdf-verifier rspec
