language: ruby

rvm:
  - ruby-head
  - 2.7
  - 2.6
  - 2.5
  - 2.4
  - 2.3
matrix:
  allow_failures:
    - rvm: ruby-head
before_install:
  - sudo apt-get install -y default-jre unzip wget
install:
  - bundle install --without development
  - wget http://software.verapdf.org/releases/1.14/verapdf-greenfield-1.14.8-installer.zip -O /tmp/verapdf-installer.zip
  - unzip /tmp/verapdf-installer.zip -d /tmp/verapdf-installer
  - java -jar /tmp/verapdf-installer/*/verapdf-izpack-installer-*.jar verapdf-auto-install.xml
script:
  - rspec
